### ISSUE TITLE
License checker fails on okta.yaml file

### ISSUE THREAD

**Issue by wayneearl-okta** [okta/okta-java-parent#20]
When building an application that incorporates any of various Okta libraries (okta-sdk-*), running with the "ci" profile (-Pci) fails on the license check step if an okta.yaml file has been included.

**More Information**
Configuring a project to use various Okta libraries includes use of an okta.yaml file. (See here: https://github.com/okta/okta-sdk-java#configuration-reference) In addition, instructions for building various projects (e.g., https://github.com/okta/okta-sdk-java/wiki/Build-It) include recommendations to run Maven with the "ci" profile: mvn clean install -Pci. If a developer has included an Okta configuration file (e.g., src/main/resources/okta.yaml), this file will fail the license validation step.

One resolution for this would be to add "**/okta.yaml" to the list of excludes in the license checker configuration (within the /parent/pom.xml of this project).

**Comment by bdemers** [comment]
@wayneearl-okta sorry it has taken so long to get to this, were you seeing this when you ran `-Pci` from the root or a submodule?

**Comment by bdemers** [comment]
This is expected, headers can be added to new files using `mvn license:format`
